# Generated by Django 5.2.4 on 2025-07-16 19:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('verbose_name_ru', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Класс аварии',
                'verbose_name_plural': 'Классы аварий',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlarmTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название таблицы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Таблица аварий',
                'verbose_name_plural': 'Таблицы аварий',
            },
        ),
        migrations.CreateModel(
            name='AlarmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.CharField(choices=[('discrete', 'Дискретное событие'), ('analog', 'Аналоговое событие'), ('change', 'Изменение события')], max_length=20, verbose_name='Способ наблюдения')),
                ('channel', models.CharField(blank=True, max_length=100, verbose_name='Имя канала')),
                ('limit_type', models.CharField(blank=True, choices=[('low', 'Ограничение снизу'), ('high', 'Ограничение сверху'), ('low_high', 'Ограничение снизу и сверху')], max_length=20, verbose_name='Тип ограничения')),
                ('limit_config_type', models.CharField(choices=[('values', 'Значения пределов'), ('channels', 'Каналы пределов')], default='values', max_length=20, verbose_name='Тип настройки пределов')),
                ('low', models.FloatField(default=0.0, verbose_name='Нижний предел')),
                ('high', models.FloatField(default=0.0, verbose_name='Верхний предел')),
                ('discrete_val', models.FloatField(default=0.0, verbose_name='Значение предела для дискретного сигнала')),
                ('msg', models.TextField(verbose_name='Текст сообщения')),
                ('hyst_low', models.FloatField(default=0.0, verbose_name='Гистерезис нижнего предела')),
                ('hyst_high', models.FloatField(default=0.0, verbose_name='Гистерезис верхнего предела')),
                ('ch_low', models.CharField(blank=True, max_length=100, verbose_name='Канал нижнего предела')),
                ('ch_high', models.CharField(blank=True, max_length=100, verbose_name='Канал верхнего предела')),
                ('confirm_method', models.CharField(choices=[('rep_ack', 'Квитирование деактивированной тревоги')], default='manual', max_length=20, verbose_name='Способ подтверждения')),
                ('prior', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Приоритет тревоги')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('alarm_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_configs', to='alarms.alarmclass', verbose_name='Класс тревоги')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='alarms.alarmtable', verbose_name='Таблица сообщений')),
            ],
            options={
                'verbose_name': 'Конфигурация аварии',
                'verbose_name_plural': 'Конфигурации аварий',
                'ordering': ['alarm_class', 'prior'],
            },
        ),
    ]
