# Generated by Django 5.2.4 on 2025-07-21 00:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('verbose_name_ru', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Класс тревоги',
                'verbose_name_plural': 'Классы тревог',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlarmTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='Уникальный номер таблицы для внешних систем', unique=True, verbose_name='Номер таблицы')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название таблицы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Таблица тревог',
                'verbose_name_plural': 'Таблицы тревог',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('verbose_name_ru', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Способ подтверждения',
                'verbose_name_plural': 'Способы подтверждения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LimitConfigType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('verbose_name_ru', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Тип настройки пределов',
                'verbose_name_plural': 'Типы настройки пределов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LimitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('verbose_name_ru', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Тип ограничения',
                'verbose_name_plural': 'Типы ограничений',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('verbose_name_ru', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Способ наблюдения',
                'verbose_name_plural': 'Способ наблюдения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlarmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100, unique=True, verbose_name='Имя канала')),
                ('msg', models.TextField(verbose_name='Текст сообщения')),
                ('prior', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Приоритет тревоги')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='Нижний предел')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='Верхний предел')),
                ('ch_low', models.CharField(blank=True, max_length=100, null=True, verbose_name='Канал нижнего предела')),
                ('ch_high', models.CharField(blank=True, max_length=100, null=True, verbose_name='Канал верхнего предела')),
                ('hyst_low', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Гистерезис нижнего предела')),
                ('hyst_high', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Гистерезис верхнего предела')),
                ('discrete_val', models.FloatField(blank=True, null=True, verbose_name='Значение предела для дискретного сигнала')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('alarm_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_configs', to='alarms.alarmclass', verbose_name='Класс тревоги')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='alarms.alarmtable', verbose_name='Таблица тревог')),
                ('confirm_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_configs', to='alarms.confirmmethod', verbose_name='Способ подтверждения')),
                ('limit_config_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_configs', to='alarms.limitconfigtype', verbose_name='Тип настройки пределов')),
                ('limit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_configs', to='alarms.limittype', verbose_name='Тип ограничения')),
                ('logic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_configs', to='alarms.logic', verbose_name='Способ наблюдения')),
            ],
            options={
                'verbose_name': 'Конфигурация тревоги',
                'verbose_name_plural': 'Конфигурации тревог',
                'ordering': ['id'],
            },
        ),
    ]
