# Generated by Django 4.2.7 on 2025-07-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='limit_config_type',
            field=models.CharField(choices=[('values', 'Значения пределов'), ('channels', 'Каналы пределов')], default='values', max_length=20, verbose_name='Тип настройки пределов'),
        ),
    ]
