# Generated by Django 5.2.4 on 2025-07-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('verbose_name_ru', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Логика',
                'verbose_name_plural': 'Логики',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='alarmconfig',
            name='logic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_configs', to='alarms.logic', verbose_name='Способ наблюдения'),
        ),
    ]
