# Generated by Django 4.2.7 on 2025-07-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_alarmconfig_limit_config_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmconfig',
            name='event',
        ),
        migrations.AlterField(
            model_name='alarmconfig',
            name='logic',
            field=models.CharField(choices=[('discrete', 'Дискретное событие'), ('analog', 'Аналоговое событие'), ('change', 'Изменение события')], max_length=20, verbose_name='Способ наблюдения'),
        ),
    ]
