# Generated by Django 5.2.4 on 2025-07-16 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_confirmmethod_alter_alarmconfig_confirm_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('verbose_name_ru', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Тип ограничения',
                'verbose_name_plural': 'Типы ограничений',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='alarmconfig',
            name='limit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_configs', to='alarms.limittype', verbose_name='Тип ограничения'),
        ),
    ]
