# Generated by Django 4.2.7 on 2025-07-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_remove_alarmconfig_event_alter_alarmconfig_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmconfig',
            name='alarm_class',
            field=models.CharField(choices=[('error', 'Ошибка'), ('warn', 'Предупреждение'), ('info', 'Информирование')], max_length=20, verbose_name='Класс тревоги'),
        ),
        migrations.AlterField(
            model_name='alarmconfig',
            name='confirm_method',
            field=models.CharField(choices=[('', '---------'), ('rep_ack', 'Квитирование деактивированной тревоги')], default='manual', max_length=20, verbose_name='Способ подтверждения'),
        ),
    ]
