# Generated by Django 5.2.4 on 2025-07-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0004_alter_alarmconfig_alarm_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='alarmconfig',
            name='confirm_method',
            field=models.CharField(choices=[('rep_ack', 'Квитирование деактивированной тревоги')], default='manual', max_length=20, verbose_name='Способ подтверждения'),
        ),
    ]
