# Generated by Django 5.2.4 on 2025-07-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0005_alarmconfig_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmtable',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
    ]
